version: '2.1'

services:
  reyes_magos:
    image: yeasy/simple-web:latest
    restart: unless-stopped
    ports:
      - "80:80"
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8123'
      - 'traefik.frontend.rule=Host:reyesmagos.josezambudiobernabeu.com'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.docker.network=proxy-network'
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
