version: '2.3'

services:
  # TODO nextcloud -> app
  nextcloud:
    image: nextcloud_nextcloud
    build:
      context: ./nextcloud
      args:
        TAG: 16.0.1-apache
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_CLI_URL=${NEXTCLOUD_CLI_URL}
      - NEXTCLOUD_PROTOCOL=${NEXTCLOUD_PROTOCOL}
    volumes:
      - nextcloud-volume:/var/www/html
      - nextcloud-apps-volume:/var/www/html/custom_apps
      - nextcloud-config-volume:/var/www/html/config
      - nextcloud-data-volume:/var/www/html/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:nextcloud.${DOMAIN}'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.docker.network=proxy-network'
    networks:
      - postgres-network
      - proxy-network
      - redis-network
    # logging:
    #   driver: 'journald'
    #   options:
    #     tag: 'nextcloud'

volumes:
  nextcloud-volume: {}
  nextcloud-apps-volume: {}
  nextcloud-config-volume: {}
  nextcloud-data-volume: {}

networks:
  postgres-network:
    external: true
  proxy-network:
    external: true
  redis-network:
    external: true
