version: '2.3'

services:
  fail2ban:
    build:
      context: ./fail2ban/fail2ban
    restart: unless-stopped
    environment:
      - PUSHBULLET_ACCESS_TOKEN=${F2B_PUSHBULLET_ACCESS_TOKEN}
      - TELEGRAM_TOKEN=${F2B_TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${F2B_TELEGRAM_CHAT_ID}
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - /var/log/journal:/var/log/journal:ro
      - fail2ban-socket-volume:/var/run/fail2ban:z
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: stat /var/run/fail2ban/fail2ban.sock
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    logging:
      driver: 'journald'
      options:
        tag: 'fail2ban'

  f2b-tg-bot:
    build:
      context: ./fail2ban/f2b-tg-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${F2B_TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${F2B_TELEGRAM_CHAT_ID}
    depends_on:
      - fail2ban
    volumes:
      - fail2ban-socket-volume:/var/run/fail2ban:z
    network_mode: bridge
    # healthcheck:
    #   test: nc -z 127.0.0.1 9000
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 10s

volumes:
  fail2ban-socket-volume: {}

networks:
  default:
