version: '2.1'

services:
  rtorrent:
    build:
      context: ./rtorrent
    image: rtorrent_rtorrent
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "6890-6890:6890-6890"
      - "6881:6881/udp"
    environment:
      - RT_UID=${RTORRENT_UID:-1000}
      - RT_GID=${RTORRENT_GID:-1000}
      # - RT_LOG_LEVEL=${RTORRENT_LOG_LEVEL:-info}
      # - RT_PORT_RANDOM=${RT_PORT_RANDOM:-no}
      # - RT_DHT_PORT=${RTORRENT_DHT_PORT:-6881}
    volumes:
      - rtorrent-incoming-volume:/data/incoming
      - rtorrent-session-volume:/data/session
      - rtorrent-downloads-volume:/data/downloads:z
      - rtorrent-watch-volume:/data/watch
    networks:
      - rtorrent-network
    healthcheck:
      test: nc -z 127.0.0.1 5000
      interval: 30s
      timeout: 30s
      retries: 3

  flood:
    build:
      context: ./flood
    restart: unless-stopped
    image: rtorrent_flood
    ports:
      - "3000:3000"
    volumes:
      - flood-volume:/data
    environment:
      - RTORRENT_VER=${RTORRENT_VER:-0.9.7}
      - LIBTORRENT_VER=${LIBTORRENT_VER:-0.13.7}
      - MEDIAINFO_VER=${MEDIAINFO_VER:-18.05}
      - FLOOD_VER=${FLOOD_VER:-master}
      - FLOOD_SECRET=${FLOOD_SECRET:-supersecret}
      - RTORRENT_SCGI_HOST=rtorrent
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:flood.${DOMAIN}'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.frontend.auth.basic=${BASIC_AUTH}'
      - 'traefik.docker.network=proxy-network'
    networks:
      - rtorrent-network
      - proxy-network
    depends_on:
      - rtorrent
    healthcheck:
      test: nc -z 127.0.0.1 3000
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  rtorrent-session-volume: {}
  rtorrent-watch-volume: {}
  flood-volume: {}
  rtorrent-incoming-volume:
    external: true
  rtorrent-downloads-volume:
    external: true

networks:
  rtorrent-network:
  proxy-network:
    external: true
