version: '2.1'

services:
  flood:
    build:
      args:
        ARCH: arm64v8

  jackett:
    image: linuxserver/jackett:arm64v8-v0.14.125-ls58

  sonarr:
    image: linuxserver/sonarr:arm64v8-2.0.0.5344-ls53

  radarr:
    image: linuxserver/radarr:arm64v8-5.14
