version: "2.1"

services:
  plex:
    build:
      context: ./plex
    network_mode: "host"
    ports:
      - 32400:32400
    restart: unless-stopped
    environment:
      - PUID=${PLEX_PUID:-1000}
      - PGID=${PLEX_PGID:-1000}
    volumes:
      - plex-config-volume:/config
      - rtorrent-downloads-volume:/data:z
    healthcheck:
      test: nc -z 127.0.0.1 32400
      interval: 5s
      timeout: 10s
      retries: 7

volumes:
  plex-config-volume: {}
  rtorrent-downloads-volume:
    external: true

# networks:
#   proxy-network:
#     external: true
