version: '2.3'

services:

  cron:
    image: nextcloud_nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    volumes:
      - nextcloud-volume:/var/www/html
      - nextcloud-apps-volume:/var/www/html/custom_apps
      - nextcloud-config-volume:/var/www/html/config
      - nextcloud-data-volume:/var/www/html/data
    entrypoint: /cron.sh
    networks:
      - postgres-network
      - redis-network

volumes:
  nextcloud-volume: {}
  nextcloud-apps-volume: {}
  nextcloud-config-volume: {}
  nextcloud-data-volume: {}

networks:
  postgres-network:
    external: true
  redis-network:
    external: true
