version: "2.1"

services:
  plex:
    build:
      context: ./plex
    network_mode: "host"
    ports:
      - 32400:32400
    restart: always
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data
