global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
    monitor: 'rpi3b-stack-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rpi3b'
    static_configs:
      - targets: ['192.168.1.62:9100']

# rule_files:
#   - "rules.yml"
